name: JimAllison
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49323
title: Jim Allison
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0a08'
    - '#9bd4ff'
    - '#77624f'
    - '#3d45ff'
  brandStrength: 0.8125
  lightness: 0.8623427811544389
  saturation: 0.26489510224200785
  rhythmicContrast: 0.8846255601383746
purpose: []
