name: JimAllison
favicon: null
layout_spectrum: 0.9622610108926892
typography_spectrum: 0.11452746414579451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9351755995303392
  lightness: 0.8623427811544389
  saturation: 0.26489510224200785
  rhythmicContrast: 0.8846255601383746
purpose: []
